### PR TITLE
Support Brave browser

### LINKED ISSUE #17: Use with Brave browser & possible workaround
I decided to see if I could get this and the associated web extension running from Brave.

Since Brave is chromium based, I tried running `bukubrow --install-chromium `.  This does not fully work.  

Copying `~/.config/chromium/NativeMessagingHosts/com.samh.bukubrow.json`
to the `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/` directory
appears to fix the issue.

### PR DESCRIPTION
**Pull request by joeweaver**
I've added what I think are all the modifications to support an `--install Brave` option on Linux to address issue #17   Note that Rust is entirely new to me (really helpful compiler error messages!) and I have no way to test on MacOS.

### CODE REVIEW

**Comment by samhh** [comment]
Hey, thank you for this!

Would it be possible to copy [Browserpass's config location](https://github.com/browserpass/browserpass-native/blob/master/Makefile) for Brave on macOS?

Also be sure to run `rustfmt` so that code can pass CI. :slightly_smiling_face:

**Comment by samhh** [comment]
Note to self: Update readme along with the changelog when this is merged.

**Comment by joeweaver** [comment]
I'd be happy to. It may be a few days before I can get to it.

**Comment by samhh** [comment]
Closing in favour of #22.

**Pull request closed without merging**
